### ISSUE TITLE
Update CSS template

### ISSUE THREAD

**Issue by ldexterldesign** [karfcz/grunt-sprite-packer#5]
Hey,

https://github.com/karfcz/grunt-sprite-packer/blob/master/test/fixtures/sprites.css.tpl#L1 - shouldn't this be vanilla CSS?

Regards,

PS thanks for your work on this plugin ;)

**Comment by karfcz** [comment]
No, this is a handlebars template file (hence the extension .css.tpl). It is processed with generated  metadata and the result will be vanilla css.
