### ISSUE TITLE
Comparison with grunt-spritesmith

### ISSUE THREAD

**Issue by Strajk** [karfcz/grunt-sprite-packer#7]
Hi there, appreciate your work, but I would be interested about motivation and comparison with widely used https://github.com/Ensighten/grunt-spritesmith

**Comment by karfcz** [comment]
Hi, I don't know about grunt-spritesmith but it looks similar to my sprite packer. When I wrote sprite packer about two years ago, I didn't found any usable tool that would use bin-tree packer algorithm and templated output, so I have written it myself. Not sure if spritesmith did exist at that time or if it had all the features it has now. Not a big deal. I have not tried spritesmith, so use what fits your needs better. We use sprite packer together with stylus in our team every day and it works fine for us.
