### ISSUE TITLE
Add overall width and height as an optional variable to the css template

### ISSUE THREAD

**Issue by hydrotik** [karfcz/grunt-sprite-packer#9]
Scene7 uses the overall sprite height and width as URL vars in the image path. Would be great to have access to those in the template.

**Comment by karfcz** [comment]
I don't know what is Scene7 but overall sprite dimensions are accessible in the template as {width} and {height} variables.

**Comment by hydrotik** [comment]
Thank you for the quick reply. Don't the height and width vars indicate individual sprite height and width within the png, but not the total height and width of the entire png file that is generated? I'm interested in the latter. Also, Scene7 is Adobe's CDN service for static assets such as images, video, and some other non-binary files. It allows the rendering of images in multiple formats and sizes just my adding variables to the URL.

**Comment by karfcz** [comment]
There are both dimensions in the template - global (top level) variables for total width and height of the png file as well as width/height vars for each sprite (inside the "sprites" array). See readme https://github.com/karfcz/grunt-sprite-packer#optionstemplate
